name: zoho_gatherly
description: "Event Gathering Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

 #StateManagements
  provider:

  #Networks
  connectivity_plus: ^6.0.3

  #Local Storage
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.0
  sqflite: ^2.0.3

  #Widgets
  image_picker: ^0.8.7+4
  size_setter:
  flick_video_player: ^0.8.0
  path_drawing: ^1.0.0
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  fonts:
    - family: SeymourOne
      fonts:
        - asset: assets/fonts/SeymourOne-Regular.ttf

    - family: sfCompactDisplay
      fonts:
        - asset: assets/fonts/sf-compact-display-medium.otf

  assets:
    - assets/
    - assets/videos/
    - assets/images/
    - assets/fonts/
    - assets/json/language/